### ISSUE TITLE
No highlight class added when a link is supplied

### ISSUE THREAD

**Issue by acheloos-m** [tompetrus/oracle-apex-tree-search-show#1]
Hey, congrats on the plugin - really helpfull.

I've discovered, that when you add any value to the tree regions 'link' column, the highlighting will stop working while the collapse / expand mechanism will work anyway. 
Without this supplied, anything works as expected.

Any Ideas?
Regards Martin

**Comment by acheloos-m** [comment]
Okay got it. 

Inj the sources, js tries to reference a span for highlighting. 
`sel.find("span.a-TreeView-label").addClass(self.options.matchClass);`

by simply adding 
`sel.find("a.a-TreeView-label").addClass(self.options.matchClass);`

also the href tree entrys are highlighted.

**Comment by tompetrus** [comment]
@acheloos-m So it's actually kind of a bug? :-) I'll see what I can do in a bugfix soon!
