### ISSUE TITLE
Can't get the JS Search Function syntax correct to override the default value

### ISSUE THREAD

**Issue by DavidCle** [tompetrus/oracle-apex-tree-search-show#2]
Hi,
I am trying to set the Search Function (JS) text box. I have tried all sorts of combinations but can't even get the default example to work. I have entered the following:

function (n,term) { return n.label.toLowerCase().indexOf(term.toLowerCase())!==-1; }

but it displays the error:

Uncaught TypeError: self.options.matchFunction is not a function
    at match (apex.widget.treeView.searchShow.js:41)
    at HTMLLIElement.<anonymous> (widget.treeView.min.js?v=5.1.2.00.09:1)

Any thoughts on what I am doing wrong !

Kind Regards,
Dave

**Comment by tompetrus** [comment]
Hi David,  
  
It took a while to sit down to find the issue, mainly because of a lack of spare time, and secondly because I initially was looking at the wrong place at first :)  
This fixes it, I verified. Any more questions or issue, feel free.
